import Head from "next/head";
import Link from "next/link";
import Base from "../components/base";
import conectarDB from "../lib/dbConnect";
import Movie from "../models/Movie";

export default function Home({ movies }) {
  console.log(movies);
  return (
    <>
    <Base />
    <div>
      <Head>
        
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <h1>Produtos em Estoque</h1>
        
        <div className="tudo">
        {movies.map(({ _id, nome, descricao }) => (
          
          <div className="bloco" key={_id}>
            <div className="bloc">
              <div className="bloco_nome">{nome}</div>
              <p className="fw-light">{descricao}</p>
              <Link href={`/${_id}`}>
                <a className="abrir">Abrir</a>
              </Link>
            </div>
          </div>
        ))}
        </div>
      </main>
    </div>
    </>
  );
}

export async function getServerSideProps() {
  try {
    await conectarDB();

    const res = await Movie.find({});

    const movies = res.map((doc) => {
      const movie = doc.toObject();
      movie._id = `${movie._id}`;
      return movie;
    });

    // console.log(res)

    return { props: { movies } };
  } catch (error) {
    console.log(error);
  }
}
