import Head from "next/head";
import Link from "next/link";
import Base from "../components/base";
import conectarDB from "../lib/dbConnect";
import Movie from "../models/Movie";
import Funcionario from "../models/Funcionario";


export default function Home({ movies, func }) {
  //console.log(movies);
  return (
    <>
    <Base />
    <div>
      <Head>
        
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
         {/* Relatórios Produtos */}
        <h1>Relatório do Sistema</h1>
        
        <h3 className="tab_prod">Produtos</h3>
        <tr>
        <th className="tab">Código</th>
        <th className="tab">Nome</th>
        <th className="tab">Descrição</th>
        <th className="tab">Validade</th>
        <th className="tab">Quantidade</th>
        <th className="tab">Valor por unidade</th>
    </tr>
        {movies.map(({ _id, nome,codigo, descricao, valor, qtd , data}) => (
          
          <div className="" key={_id}> 
        <table className="tabela" >   
    <tr>
        <td className="tab">{codigo}</td>
        <td className="tab">{nome}</td>
        <td className="tab">{descricao}</td>
        <td className="tab">{data}</td>
        <td className="tab">{qtd}</td>
        <td className="tab">R${valor}</td>
    </tr>
        </table>
              
          
          </div>
        ))}
        
         {/* Relatórios funcionarios */}
        <h3 className="tab_prod">Funcionarios</h3>
        <tr>
        <th className="tab">Código</th>
        <th className="tab">Nome</th>
        <th className="tab">Data de nascimento</th>
        <th className="tab">Telefone</th>
        <th className="tab">Funcao</th>
        <th className="tab">Salario</th>
    </tr>
        {func.map(({ _id, nome,codigo, endereco, dataNascimento, salario,telefone, funcao  }) => (
          
          <div className="" key={_id}> 
        <table className="tabela" >   
    <tr>
        <td className="tab">{codigo}</td>
        <td className="tab">{nome}</td>
        <td className="tab">{dataNascimento}</td>
        <td className="tab">{telefone}</td>
        <td className="tab">{funcao}</td>
        <td className="tab">R${salario}</td>
    </tr>
        </table>
              
          
          </div>
        ))}
        
      </main>
    </div>
    </>
  );
}

export async function getServerSideProps() {
  try {
    await conectarDB();
    
    //produtos infos
    const res = await Movie.find({});
    const movies = res.map((doc) => {
      const movie = doc.toObject();
      movie._id = `${movie._id}`;
      return movie;
    });

    //funcionario infos
    const resa = await Funcionario.find({});
    const func = resa.map((doc) => {
      const funcion = doc.toObject();
      funcion._id = `${funcion._id}`;
      return funcion;
    });

    // console.log(res)

    return { props: { movies, func } };
  } catch (error) {
    console.log(error);
  }
}

